///////////////////////////////////////////////////////////
//  Effect.cs
//  Implementation of the Class Effect
//  Generated by Enterprise Architect
//  Created on:      04-ноя-2014 12:01:06
//  Original author: Samurai
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using System.Windows.Forms;
using System;


public abstract class Effect 
{
    public abstract string Name();

	//~Effect(){}
}//end Effect

public abstract class EffectsUnit : Effect
{
    public virtual void Leader(ref Unit u,ref int res,ref int leadership,ref int ReRoll,Game _g)
    { 
    }
}
public abstract class EffectsWeapons : Effect
{
    public virtual void OnShoot(ref Wound w, ref List<Wound> l, ref int ReRoll, Game _g)
    {
    }
    public virtual void OnWound(ref Wound w, ref List<Wound> l, ref int ReRoll, Game _g)
    {
    }
}
public abstract class EffectsModel : Effect
{
    public virtual void EndTurn(BasicModel m)
    {

    }
    public virtual void EndEnemyTurn(BasicModel m)
    {

    }
}
/// <summary>
/// hfgpihbtpihrt/h
/// </summary>
public class baldestorm : EffectsWeapons
{
    public override void OnShoot(ref Wound w, ref List<Wound> l, ref int ReRoll, Game _g)
    {
        if(w.dWound==6)
        {
            w.ap = 2;
        }
    }
}