///////////////////////////////////////////////////////////
//  Effect.cs
//  Implementation of the Class Effect
//  Generated by Enterprise Architect
//  Created on:      04-ноя-2014 12:01:06
//  Original author: Samurai
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using System.Windows.Forms;
using System;


public abstract class Effect 
{
    public abstract string Name();

	//~Effect(){}
}//end Effect

public abstract class EffectsUnit : Effect
{
    public virtual void Leader(Unit u,int res,int leadership,Game _g)
    { 
    }
}
public abstract class EffectsWeapons : Effect
{
    public virtual List<Wound> OnShoot(Wound w,List<Wound> l,Game _g)
    {
        return l;
    }
    public virtual List<Wound> OnWound(Wound w, List<Wound> l, Game _g)
    {
        return l;
    }
}
public abstract class EffectsModel : Effect
{
    public virtual void EndTurn(BasicModel m)
    {

    }
    public virtual void EndEnemyTurn(BasicModel m)
    {

    }
}
