///////////////////////////////////////////////////////////
//  Game.cs
//  Implementation of the Class Game
//  Generated by Enterprise Architect
//  Created on:      04-ноя-2014 12:03:36
//  Original author: User
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using System.Windows.Forms;

public interface PfaseSr
{
    void MousClick(int x, int y,Game _g);
    void ActButtonClick(Game _g);
}


public class PfaseNofing:PfaseSr
{
    public void MousClick(int x, int y, Game _g) 
    {

    }
    public void ActButtonClick(Game _g)
    {
        
    }
}


public class PfaseShoot : PfaseSr
{
    public void MousClick(int x, int y, Game _g)
    {
        Unit un=_g.IsMap.FindUnit(x, y);
        if(un !=null)
        {
            if (un.w_Player == _g.PlayerNow())
                _g.Sourse = un;
            else
                _g.Target = un;
        }
    }
    public void ActButtonClick(Game _g)
    {
        _g.Shooting();
    }
}

public enum Pfase
{
    Move,
    Shoot,
    Charge,
    End
}

public class Game 
{
    public PfaseSr NowPfaseStr;
    public PfaseSr NofingPf = new PfaseNofing();
    public PfaseSr ShootPf = new PfaseShoot();
	private int NowPlayer;
    public Pfase NowPhase { get; private set; }
    public Player[] Players { get; private set; }
    public Map IsMap;
    public MapInterfeise IsMapInter = new MapInterfeise();
    public MiniMap IsMiniMap = new MiniMap();
	private int Turn;
    public Unit Target {get;set;}
    public Unit Sourse {get;set;}
    public intMission NowMission;
    public DiceInt DiceGen { get; private set; }

    public  bool IsNowPfase(Pfase p)
    {
        if (p == NowPhase)
            return true;
        return false;
    }

    private void EndPfase()
    {
        foreach (Player p in Players)
        {
            foreach (Unit U in p.PlayersUnit)
            {
                U.EndPfase(this);
            }
        }
        switch(NowPhase)
        {
            case Pfase.Move:
                break;
            case Pfase.Shoot:
                break;
            case Pfase.Charge:
                break;
        }
    }

    private void BeginPfase()
    {
        foreach (Player p in Players)
        {
            foreach (Unit U in p.PlayersUnit)
            {
                U.EndPfase(this);
            }
        }
        switch (NowPhase)
        {
            case Pfase.Move:
                MessageBox.Show("Фаза движения");
                NowPfaseStr = NofingPf;
                break;
            case Pfase.Shoot:
                MessageBox.Show("Фаза стрельбы");
                NowPfaseStr = ShootPf;
                break;
            case Pfase.Charge:
                MessageBox.Show("Фаза атаки");
                NowPfaseStr = NofingPf;
                break;
        }
    }

    public void NextPfase()
    {
        EndPfase();
        NowPhase++;

        if(NowPhase==Pfase.End)
        {
            NowPhase = Pfase.Move;
            NowPlayer++;
            Unit p=Target;
            Target = Sourse;
            Sourse = p;
            if(NowPlayer==2)
            {
                NowPlayer = 0;

                if(Turn==5)
                {
                    if(DiceGen.D6()<=4)
                    {
                        MessageBox.Show("Конец игры");
                    }
                }
                if (Turn == 6)
                {
                    if (DiceGen.D6() <= 5)
                    {
                        MessageBox.Show("Конец игры");
                    }
                }
                if (Turn == 7)
                {
                    MessageBox.Show("Конец игры");
                } 
                Turn++;
                MessageBox.Show("Новый ход");
            }
            else
            {
                MessageBox.Show("Следующий игрок");
            }
        }
        else
        {
            //MessageBox.Show("Новая фаза");
        }
        BeginPfase();
    }

    public Player PlayerNow()
    {
        return Players[NowPlayer];
    }

    public void MouseClick(int x,int y)
    {
        NowPfaseStr.MousClick(x, y,this);
    }

    public void ClickActionButton()
    {
       /* switch(NowPhase)
        {
            case Pfase.Move:
                break;
            case Pfase.Shoot:
                Shooting(Target, 0, Sourse);
                break;
            case Pfase.Charge:
                break;
        }*/
        NowPfaseStr.ActButtonClick(this);
    }

    public Game(Player P1, Player P2, DiceInt DiceG)
    {
        Players = new Player[2];
        Players[0] = P1;
        Players[1] = P2;
        DiceGen = DiceG;
        NowMission = new EturnalWar1();
        NowPhase = Pfase.Move;
        Sourse = Players[0].PlayersUnit[0];
        Target = Players[1].PlayersUnit[0];
        Turn = 1;
        NowPlayer = 0;
        List<Unit> LUnit = new List<Unit> { };
        foreach (Player p in Players)
        {
            LUnit.AddRange(p.GetUnits());
        }
        IsMap = new Map(LUnit);
    }

	public Game(DiceInt DiceG)
    {
        NowPfaseStr = ShootPf;
        List<Unit> LUnit = new List<Unit> {};
        NowMission = new EturnalWar1();
        DiceGen = DiceG;
        Players = new Player[2];
        Players[0] = new Player();
        Players[1] = new Player();
        NowPlayer = 0;
        NowPhase = Pfase.Shoot;
        Turn = 1;
        Sourse = Players[0].PlayersUnit[0];
        Sourse.Models[0].x += 300;
        Sourse.Models[1].x += 300;
        Sourse.Models[2].x += 300;
        Target = Players[1].PlayersUnit[0];
        foreach(Player p in Players)
        {
            LUnit.AddRange(p.GetUnits());
        }
        IsMap = new Map(LUnit);
	}

	~Game()
    {

	}
	public int Shooting(Unit Target, int WeaponTyper, Unit Sourse)
    {
        int Cover = 7;
        List<Wound> L = new List<Wound> { };
        L = Sourse.Shoot(Target,0,DiceGen);
        if (L == null)
            return 0;
        L = Target.Wonding(Sourse, L, this);
        if (L == null)
            return 0;
        Target.Save(Cover, Sourse,L, DiceGen);
		return 0;
	}

    public int Shooting()
    {
        int Cover = 7;
        List<Wound> L = new List<Wound> { };
        L = Sourse.Shoot(Target, 0, DiceGen);
        if (L == null || L.Count==0)
            return 0;
        L = Target.Wonding(Sourse, L,this);
        if (L == null || L.Count == 0)
            return 0;
        Target.Save(Cover, Sourse, L, DiceGen);
        return 0;
    }

	public void Wounding(Unit Target, Wound[] Shots, int HowManyShot)
    {

	}

}//end Game