///////////////////////////////////////////////////////////
//  Game.cs
//  Implementation of the Class Game
//  Generated by Enterprise Architect
//  Created on:      04-ноя-2014 12:03:36
//  Original author: User
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using System.Windows.Forms;

public interface PfaseSr
{
    void MousClick(int x, int y,Game _g);
    void ActButtonClick(Game _g);
    void IndependentCharecterButtonClick(Game _g);
}


public class PfaseNofing:PfaseSr
{
    public void MousClick(int x, int y, Game _g) 
    {

    }
    public void ActButtonClick(Game _g)
    {
        
    }
    public void IndependentCharecterButtonClick(Game _g)
    {

    }
}


public class PfaseShoot : PfaseSr
{
    public void MousClick(int x, int y, Game _g)
    {
        Unit un=_g.IsMap.FindUnit(x, y);
        if(un !=null)
        {
            if (un.w_Player == _g.PlayerNow())
                _g.Sourse = un;
            else
                _g.Target = un;
        }
    }
    public void ActButtonClick(Game _g)
    {
        _g.Shooting();
    }
    public void IndependentCharecterButtonClick(Game _g)
    {

    }
}

public class PfaseChose : PfaseSr
{
    public void MousClick(int x, int y, Game _g)
    {
        //Unit unit = _g.IsMap.FindUnit(x, y); //IsMap - current map
        _g.cur_model = _g.IsMap.FindModel(x, y);
        if (_g.cur_model == null)
            _g.cur_unit = null;
        else
            _g.cur_unit = _g.cur_model.w_Unit;

    }
    public void ActButtonClick(Game _g)
    {
        if (_g.cur_unit==null)
        {
            MessageBox.Show("Выберите отряд.");
        }        
        else if(_g.cur_unit.w_Player!=_g.PlayerNow())
        {
            MessageBox.Show("Этот отряд не пренадлежит вам.");
        }
        else if (_g.cur_unit.Moved != 0)
        {
            MessageBox.Show("Вы уже перемещали этот отряд.");
        }        
        else
            _g.NowPfaseStr = _g.MovePf;
    }
    public void IndependentCharecterButtonClick(Game _g)
    {

    }
}

public class PfaseMove : PfaseSr
{
    public void MousClick(int x, int y, Game _g)
    {
        BasicModel model=_g.IsMap.FindModel(x, y);
        if (model!=null)
        {
            if(model.w_Unit!=_g.cur_unit)
            {
                MessageBox.Show("Вы не можете перемещать данную модель.");
            }
            else
            {
                _g.cur_model = model;
            }
        }
        else
        {
            int en = 0;
            foreach (Unit unit in _g.Players[1-_g.NowPlayer].GetUnits())
            {
                foreach (BasicModel t_model in unit.Models)
                {
                    if((x-t_model.x)*(x-t_model.x)+(y-t_model.y)*(y-t_model.y)<=_g.enemy_distance*_g.enemy_distance)
                    {
                        MessageBox.Show("Слишком малая дистанция с врагом.");
                        en = 1;
                        break;
                    }
                }
                if (en == 1)
                    break;
            }
            if (en == 0)
            {
                if ((x - _g.cur_model.start_x) * (x - _g.cur_model.start_x) + (y - _g.cur_model.start_y) * (y - _g.cur_model.start_y) <= _g.length * _g.length)
                {
                    _g.cur_model.x = x;
                    _g.cur_model.y = y;
                    _g.cur_model.Moved = 1;
                }
                else
                {
                    MessageBox.Show("Расстояние перемещения слишком велико.");
                }
            }
        }

    }
    public void ActButtonClick(Game _g)
    {
                int i, j, k;
        int [,]m= new int[_g.cur_unit.Models.Count, _g.cur_unit.Models.Count];
        for (i = 0; i < _g.cur_unit.Models.Count; i++)
        {
            for (j = 0; j < _g.cur_unit.Models.Count; j++)
            {
                m[i, j] = 0;
            }
        }
        i=0;
        foreach (BasicModel model in _g.cur_unit.Models)
        {
            j=0;
            foreach (BasicModel temp_m in _g.cur_unit.Models)
            {
                if (temp_m != model)
                {
                    if ((model.x - temp_m.x) * (model.x - temp_m.x) + (model.y - temp_m.y) * (model.y - temp_m.y) <= _g.distance * _g.distance)
                    {
                        m[i, j] = 1;
                        m[j, i] = 1;
                        for(k=0; k<_g.cur_unit.Models.Count; k++)
                        {
                            if (m[j, k] == 1)
                                m[i, k] = 1;
                            if (m[i, k] == 1)
                                m[j, k] = 1;
                        }
                    }
                }
                j++;
            }
            i++;
        }
        int cor = 0, t;
        for (i = 0; i < _g.cur_unit.Models.Count; i++)
        {
            t = 1;
            for (j = 0; j < _g.cur_unit.Models.Count; j++)
            {
                if(m[i, j]==0)
                {
                    t = 0;
                }
            }
            if(t==1)
            {
                cor = 1;
                break;
            }
        }
        if(cor==0)
        {
            MessageBox.Show("Дистанция между моделями некорректна.");
        }
        else
        {
            foreach (BasicModel model in _g.cur_unit.Models)
            {
                model.start_x = model.x;
                model.start_y = model.y;
            }
            _g.cur_model.w_Unit.Moved = 1;
            _g.NowPfaseStr = _g.ChosePf;
        }
    }
    public void IndependentCharecterButtonClick(Game _g)
    {

    }
}

public enum Pfase
{
    Move,
    Shoot,
    Charge,
    End
}

public class Game 
{
    public PfaseSr NowPfaseStr;
    public PfaseSr MovePf = new PfaseMove();
    public PfaseSr ChosePf = new PfaseChose();
    public PfaseSr NofingPf = new PfaseNofing();
    public PfaseSr ShootPf = new PfaseShoot();
	public int NowPlayer;
    public Pfase NowPhase { get; private set; }
    public Player[] Players { get; private set; }
    public Map IsMap;
    public MapInterfeise IsMapInter = new MapInterfeise();
    public MiniMap IsMiniMap = new MiniMap();
	private int Turn;
    public Unit Target {get;set;}
    public Unit Sourse {get;set;}
    public intMission NowMission;
    public BasicModel cur_model;
    public Unit cur_unit;
    public int length = 600;
    public int distance = 200;
    public int enemy_distance = 100;
    public int friend_distance = 100;
    public DiceInt DiceGen { get; private set; }

    public  bool IsNowPfase(Pfase p)
    {
        if (p == NowPhase)
            return true;
        return false;
    }

    private void EndPfase()
    {
        foreach (Player p in Players)
        {
            foreach (Unit U in p.PlayersUnit)
            {
                U.EndPfase(this);
            }
        }
        switch(NowPhase)
        {
            case Pfase.Move:
                break;
            case Pfase.Shoot:
                break;
            case Pfase.Charge:
                foreach (Unit unit in Players[NowPlayer].GetUnits())
                {
                    foreach (BasicModel model in unit.Models)
                    {
                        model.Moved = 0;
                    }
                    unit.Moved = 0;
                }
                break;
        }
    }

    private void BeginPfase()
    {
        foreach (Player p in Players)
        {
            foreach (Unit U in p.PlayersUnit)
            {
                U.EndPfase(this);
            }
        }
        switch (NowPhase)
        {
            case Pfase.Move:
                MessageBox.Show("Фаза движения");
                NowPfaseStr = ChosePf;
                break;
            case Pfase.Shoot:
                MessageBox.Show("Фаза стрельбы");
                NowPfaseStr = ShootPf;
                break;
            case Pfase.Charge:
                MessageBox.Show("Фаза атаки");
                NowPfaseStr = NofingPf;
                break;
        }
    }

    public void NextPfase()
    {
        EndPfase();
        NowPhase++;
        if(NowPhase==Pfase.End)
        {
            NowPhase = Pfase.Move;
            NowPlayer++;
            Unit p=Target;
            Target = Sourse;
            Sourse = p;
            if(NowPlayer==2)
            {
                NowPlayer = 0;

                if(Turn==5)
                {
                    if(DiceGen.D6()<=4)
                    {
                        MessageBox.Show("Конец игры");
                    }
                }
                if (Turn == 6)
                {
                    if (DiceGen.D6() <= 5)
                    {
                        MessageBox.Show("Конец игры");
                    }
                }
                if (Turn == 7)
                {
                    MessageBox.Show("Конец игры");
                } 
                Turn++;
                MessageBox.Show("Новый ход");
            }
            else
            {
                MessageBox.Show("Следующий игрок");
            }
        }
        else
        {
            //MessageBox.Show("Новая фаза");
        }
        BeginPfase();
    }

    public Player PlayerNow()
    {
        return Players[NowPlayer];
    }

    public void MouseClick(int x,int y)
    {
        NowPfaseStr.MousClick(x, y,this);
    }

    public void ClickActionButton()
    {
       /* switch(NowPhase)
        {
            case Pfase.Move:
                break;
            case Pfase.Shoot:
                Shooting(Target, 0, Sourse);
                break;
            case Pfase.Charge:
                break;
        }*/
        NowPfaseStr.ActButtonClick(this);
    }
    public void IndependentCharecterButtonClick()
    {
        NowPfaseStr.IndependentCharecterButtonClick(this);
    }

    public Game(Player P1, Player P2, DiceInt DiceG)
    {
        Players = new Player[2];
        Players[0] = P1;
        Players[1] = P2;
        DiceGen = DiceG;
        NowMission = new EturnalWar1();
        NowPhase = Pfase.Move;
        Sourse = Players[0].PlayersUnit[0];
        Target = Players[1].PlayersUnit[0];
        Turn = 1;
        NowPlayer = 0;
        NowPfaseStr = ChosePf;
        List<Unit> LUnit = new List<Unit> { };
        foreach (Player p in Players)
        {
            LUnit.AddRange(p.GetUnits());
        }
        IsMap = new Map(LUnit);
    }

	public Game(DiceInt DiceG)
    {
        NowPfaseStr = ShootPf;
        List<Unit> LUnit = new List<Unit> {};
        NowMission = new EturnalWar1();
        DiceGen = DiceG;
        Players = new Player[2];
        Players[0] = new Player();
        Players[1] = new Player();
        NowPlayer = 0;
        NowPhase = Pfase.Shoot;
        Turn = 1;
        Sourse = Players[0].PlayersUnit[0];
        Sourse.Models[0].x += 300;
        Sourse.Models[1].x += 300;
        Sourse.Models[2].x += 300;
        Target = Players[1].PlayersUnit[0];
        foreach(Player p in Players)
        {
            LUnit.AddRange(p.GetUnits());
        }
        IsMap = new Map(LUnit);
	}

	~Game()
    {

	}
	public int Shooting(Unit Target, int WeaponTyper, Unit Sourse)
    {
        int Cover = 7;
        List<Wound> L = new List<Wound> { };
        L = Sourse.Shoot(Target,0,DiceGen);
        if (L == null)
            return 0;
        L = Target.Wonding(Sourse, L, this);
        if (L == null)
            return 0;
        Target.Save(Cover, Sourse,L, DiceGen);
		return 0;
	}

    public int Shooting()
    {
        int Cover = 7;
        List<Wound> L = new List<Wound> { };
        L = Sourse.Shoot(Target, 0, DiceGen);
        if (L == null || L.Count==0)
            return 0;
        L = Target.Wonding(Sourse, L,this);
        if (L == null || L.Count == 0)
            return 0;
        Target.Save(Cover, Sourse, L, DiceGen);
        return 0;
    }

	public void Wounding(Unit Target, Wound[] Shots, int HowManyShot)
    {

	}

}//end Game