///////////////////////////////////////////////////////////
//  Object.cs
//  Implementation of the Class Object
//  Generated by Enterprise Architect
//  Created on:      04-ноя-2014 12:01:14
//  Original author: Samurai
///////////////////////////////////////////////////////////




public abstract class Object {

	public Object(){

	}

	~Object(){

	}

	public virtual void Dispose(){

	}

	/// 
	/// <param name="First"></param>
	/// <param name="Second"></param>
	public int InLIne(Point First, Point Second){

		return 0;
	}

	public abstract void Paint();

}//end Object