///////////////////////////////////////////////////////////
//  Player.cs
//  Implementation of the Class Player
//  Generated by Enterprise Architect
//  Created on:      04-ноя-2014 14:59:26
//  Original author: Samurai
///////////////////////////////////////////////////////////

using System.Collections.Generic;


public class Player 
{

	public List<Unit> PlayersUnit;
    public int PlayerN;

    public List<Unit> GetUnits()
    {
        return PlayersUnit;
    }

    public Player(List<Unit> L)
    {
        PlayersUnit = L;
        foreach(Unit U in L)
        {
            U.w_Player = this;
        }
    }

	public Player()
    {
        PlayersUnit = new List<Unit>{};
        PlayersUnit.Add(new Unit());
        foreach(Unit w in PlayersUnit)
        {
            w.w_Player = this;
        }
	}

	~Player()
    {

	}

}//end Player
