///////////////////////////////////////////////////////////
//  Vehicle.cs
//  Implementation of the Class Vehicle
//  Generated by Enterprise Architect
//  Created on:      04-ноя-2014 12:01:10
//  Original author: Samurai
///////////////////////////////////////////////////////////

using System;
using System.Windows.Forms;

using Warhammer;
namespace Warhammer
{
    public class Vehicle : BasicModel
    {

        private int BackArmor;
        private int FrontArmor;
        private int SideArmor;

        public override string Character()
        {
            return "We have no Vehicle";
        }

        public Vehicle()
        {

        }

        ~Vehicle()
        {

        }

        public override void Paint(PaintEventArgs e, Game _g)
        {

        }


    }//end Vehicle
}