///////////////////////////////////////////////////////////
//  Weapon.cs
//  Implementation of the Class Weapon
//  Generated by Enterprise Architect
//  Created on:      04-ноя-2014 12:01:13
//  Original author: Samurai
///////////////////////////////////////////////////////////



using System.Collections.Generic;

public enum TypeWeapon
{
    Heavy,
    Assault,
    Pistol
}


public class Weapon 
{

	protected int ArmorPenetretion = 7;
	protected int Strenght;
    protected TypeWeapon Type;
    public List<EffectsWeapons> Effects;
    protected int Shoots;
	protected int StrenghtModificationMute;
	protected int StrenghtModificationPlus;
	public BasicModel w_BasicModel;

    public virtual int IsHtHWeapon()
    {
        return 0;
    }

    public Weapon(int s,int ap,int shoots,int strmP,int strmM,List<EffectsWeapons> Eff)
    {
        ArmorPenetretion = ap;
        Shoots = shoots;
        Strenght = s;
        StrenghtModificationMute = strmM;
        StrenghtModificationPlus = strmP;
        Effects = Eff;
    }

	public Weapon()
    {
        Strenght = 4;
        Type = TypeWeapon.Assault;
        Shoots = 2;
        Effects = new List<EffectsWeapons> { };
	}

    public virtual List<Wound> HeadToHead()
    {
        return null;
    }

    public virtual List<Wound> Shoot(int moved,int bs)
    {
        List<Wound> L = new List<Wound> { };
        for (int i=0; i<Shoots;i++ )
        {
            L.Add(new Wound(Strenght, ArmorPenetretion, Effects.ToArray() ,bs,w_BasicModel));
        }
        return L;
    }

	~Weapon()
    {

	}

	public virtual void Dispose(){

	}

}//end Weapon

public class Assault : Weapon
{
    public Assault(int s,int ap,int shoots,List<EffectsWeapons> Eff)
    {
        ArmorPenetretion = ap;
        Shoots = shoots;
        Strenght = s;
        Type = TypeWeapon.Assault;
        Effects = Eff;
    }

    public override List<Wound> Shoot(int moved, int bs)
    {
        return base.Shoot(moved, bs);
    }
}
public class Heavy : Weapon
{
    public Heavy(int s,int ap,int shoots,List<EffectsWeapons> Eff)
    {
        ArmorPenetretion = ap;
        Shoots = shoots;
        Strenght = s;
        Effects = Eff;
        Type = TypeWeapon.Heavy;
    }

    public override List<Wound> Shoot(int moved, int bs)
    {
        if (moved == 0)
        {
            return base.Shoot(moved, bs);
        }
        return base.Shoot(moved, 1);
    }
}
public class Pistol : Weapon
{
    public Pistol(int s,int ap,List<EffectsWeapons> Eff)
    {
        ArmorPenetretion = ap;
        Shoots = 1;
        Strenght = s;
        Effects = Eff;
        Type = TypeWeapon.Pistol;
    }

    public override List<Wound> Shoot(int moved, int bs)
    {
        return base.Shoot(moved, bs);
    }
}
